global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "hive-mind"
    static_configs:
      - targets: ["10.1.7.158:3001"]
    metrics_path: "/metrics"
    scrape_interval: 30s
