apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ds-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    uid: ds-tempo
    access: proxy
    url: http://tempo:3200
    editable: true

  - name: Loki
    type: loki
    uid: ds-loki
    access: proxy
    url: http://loki:3100
    editable: true
